<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $accounts = array(
            array('account_type' => '7','name' => 'Office Expense','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '7','name' => 'Cartage','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '7','name' => 'Buy Goods','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '8','name' => 'Advertisement Expenses','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '8','name' => 'Rent Paid','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '9','name' => 'Current Asset','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '10','name' => 'Current Liability','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '10','name' => 'Salary Payable','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '10','name' => 'Tax Deducted Payable','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '13','name' => 'Loan Liabilities','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '14','name' => 'Loan&Advances','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '14','name' => 'Advance Salary','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '15','name' => 'Furniture','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '15','name' => 'Vehicle','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '22','name' => 'Stock Adjustment','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '23','name' => 'Production','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '24','name' => 'Income','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '24','name' => 'Discount On Purchase','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '24','name' => 'Discount Received','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '25','name' => 'Interest Received','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '26','name' => 'Capital','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '1','name' => 'Cash','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '3412045421.00','credit' => '3664588051.50','balance' => '-252542630.50','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => '2022-12-26 17:08:09','branch_id' => NULL),
            array('account_type' => '3','name' => 'Purchase','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '525.50','credit' => '0.00','balance' => '525.50','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => '2022-11-24 11:23:19','branch_id' => NULL),
            array('account_type' => '4','name' => 'Purchase Return','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '5','name' => 'Sales','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '200.00','balance' => '200.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => '2023-01-02 17:58:33','branch_id' => NULL),
            array('account_type' => '6','name' => 'Sales Return','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '7','name' => 'Expense','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => '2023-01-03 10:50:41','branch_id' => NULL),
            array('account_type' => '7','name' => 'Office Expense','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '1010.50','credit' => '0.00','balance' => '1010.50','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => '2022-11-22 16:01:10','branch_id' => NULL),
            array('account_type' => '7','name' => 'Cartage','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '7','name' => 'Buy Goods','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '8','name' => 'Advertisement Expenses','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '8','name' => 'Rent Paid','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '9','name' => 'Current Asset','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '10','name' => 'Current Liability','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '52541120.00','credit' => '0.00','balance' => '52541120.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => '2022-11-22 16:07:41','branch_id' => NULL),
            array('account_type' => '10','name' => 'Salary Payable','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '10','name' => 'Tax Deducted Payable','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '13','name' => 'Loan Liabilities','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '14','name' => 'Loan&Advances','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '200000000.00','credit' => '0.00','balance' => '200000000.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => '2022-11-21 13:29:21','branch_id' => NULL),
            array('account_type' => '14','name' => 'Advance Salary','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '15','name' => 'Furniture','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '15','name' => 'Vehicle','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '22','name' => 'Stock Adjustment','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '100021.00','balance' => '100021.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => '2022-11-29 10:26:24','branch_id' => NULL),
            array('account_type' => '23','name' => 'Production','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '24','name' => 'Income','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '24','name' => 'Discount On Purchase','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '24','name' => 'Discount Received','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '25','name' => 'Interest Received','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '26','name' => 'Capital','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '1','name' => 'Cash','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '3','name' => 'Purchase','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '4','name' => 'Purchase Return','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '24','name' => 'Discount On Purchase','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '24','name' => 'Discount Received','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '25','name' => 'Interest Received','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL),
            array('account_type' => '26','name' => 'Capital','account_number' => NULL,'bank_id' => NULL,'opening_balance' => '0.00','debit' => '0.00','credit' => '0.00','balance' => '0.00','remark' => NULL,'status' => '1','admin_id' => '2','created_at' => NULL,'updated_at' => NULL,'branch_id' => NULL)
          );
        DB::table('accounts')->insert($accounts);
    }
}
