<?php

namespace Database\Seeders;

use App\Models\Accounts\AccountGroup;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AccountGroupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accountGroups = $this->getGroups();
        AccountGroup::insert($accountGroups);
    }

    public function getGroups(): array
    {
        $accountGroups = array(
            array('id' => '1', 'sorting_number' => '0', 'name' => 'Assets', 'parent_group_id' => NULL, 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '1', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '1', 'sub_group_number' => NULL, 'sub_sub_group_number' => NULL, 'main_group_name' => 'Assets', 'sub_group_name' => NULL, 'sub_sub_group_name' => NULL, 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '0'),
            array('id' => '2', 'sorting_number' => '1', 'name' => 'Current Assets', 'parent_group_id' => '1', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => '2022-11-27 21:40:53', 'is_global' => '0'),
            array('id' => '3', 'sorting_number' => '3', 'name' => 'Bank Accounts', 'parent_group_id' => '2', 'is_reserved' => '1', 'is_allowed_bank_details' => '1', 'is_bank_or_cash_ac' => '1', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => '1', 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => 'Bank Accounts', 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => '2022-11-28 01:59:22', 'is_global' => '0'),
            array('id' => '4', 'sorting_number' => '2', 'name' => 'Cash-In-Hand', 'parent_group_id' => '2', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '1', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => '2', 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => 'Cash-In-Hand', 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => '2022-11-28 01:59:29', 'is_global' => '0'),
            array('id' => '5', 'sorting_number' => '4', 'name' => 'Deposits (Asset)', 'parent_group_id' => '2', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => '3', 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => 'Deposits (Asset)', 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => '2022-11-27 02:29:03', 'is_global' => '0'),
            array('id' => '6', 'sorting_number' => '5', 'name' => 'Loan & Advance (Asset)', 'parent_group_id' => '2', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => '4', 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => 'Loan & Advance (Asset)', 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => '2022-11-27 01:30:20', 'is_global' => '0'),
            array('id' => '7', 'sorting_number' => '6', 'name' => 'Stock-In-Hand', 'parent_group_id' => '2', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => '5', 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => 'Stock-In-Hand', 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => '2022-11-27 02:13:12', 'is_global' => '0'),
            array('id' => '8', 'sorting_number' => '7', 'name' => 'Account Receivable', 'parent_group_id' => '2', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => '6', 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => 'Sundry Debtors', 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => '2023-01-04 08:47:14', 'is_global' => '0'),
            array('id' => '9', 'sorting_number' => '8', 'name' => 'Fixed Assets', 'parent_group_id' => '1', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '1', 'sub_group_number' => '2', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Assets', 'sub_group_name' => 'Fixed Assets', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '0'),
            array('id' => '10', 'sorting_number' => '9', 'name' => 'Investments', 'parent_group_id' => '1', 'is_reserved' => '0', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '1', 'sub_group_number' => '3', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Assets', 'sub_group_name' => 'Investments', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '0'),
            array('id' => '11', 'sorting_number' => '10', 'name' => 'Liabilities', 'parent_group_id' => NULL, 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '1', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => NULL, 'sub_sub_group_number' => NULL, 'main_group_name' => 'Liabilities', 'sub_group_name' => NULL, 'sub_sub_group_name' => NULL, 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '0'),
            array('id' => '12', 'sorting_number' => '11', 'name' => 'Branch / Divisions', 'parent_group_id' => '11', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => '5', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Branch / Divisions', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '0'),
            array('id' => '13', 'sorting_number' => '12', 'name' => 'Capital Account', 'parent_group_id' => '11', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => '6', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Capital Account', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '1'),
            array('id' => '15', 'sorting_number' => '14', 'name' => 'Current Liabilities', 'parent_group_id' => '11', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => '7', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Current Liabilities', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '0'),
            array('id' => '16', 'sorting_number' => '15', 'name' => 'Duties & Taxes', 'parent_group_id' => '15', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '1', 'is_default_tax_calculator' => '1', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '2', 'sub_group_number' => '7', 'sub_sub_group_number' => '8', 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Current Liabilities', 'sub_sub_group_name' => 'Duties & Taxes', 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => '2022-11-27 02:17:19', 'is_global' => '1'),
            array('id' => '17', 'sorting_number' => '16', 'name' => 'Provisions', 'parent_group_id' => '15', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '2', 'sub_group_number' => '7', 'sub_sub_group_number' => '9', 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Current Liabilities', 'sub_sub_group_name' => 'Provisions', 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '0'),
            array('id' => '18', 'sorting_number' => '17', 'name' => 'Account Payable', 'parent_group_id' => '15', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '2', 'sub_group_number' => '7', 'sub_sub_group_number' => '10', 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Current Liabilities', 'sub_sub_group_name' => 'Sundry Creditors', 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => '2023-01-04 08:47:27', 'is_global' => '1'),
            array('id' => '19', 'sorting_number' => '18', 'name' => 'Loans (Liability)', 'parent_group_id' => '11', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => '8', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Loans (Liability)', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => '2022-11-27 02:30:51', 'is_global' => '0'),
            array('id' => '20', 'sorting_number' => '19', 'name' => 'Bank OD A/c', 'parent_group_id' => '19', 'is_reserved' => '1', 'is_allowed_bank_details' => '1', 'is_bank_or_cash_ac' => '1', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '2', 'sub_group_number' => '8', 'sub_sub_group_number' => '11', 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Loans (Liability)', 'sub_sub_group_name' => 'Bank OD A/c', 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => '2022-11-27 01:33:14', 'is_global' => '0'),
            array('id' => '21', 'sorting_number' => '20', 'name' => 'Secure Loans', 'parent_group_id' => '19', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '2', 'sub_group_number' => '8', 'sub_sub_group_number' => '12', 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Loans (Liability)', 'sub_sub_group_name' => 'Secure Loans', 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => '2022-11-27 21:41:04', 'is_global' => '0'),
            array('id' => '22', 'sorting_number' => '21', 'name' => 'Unsecure Loans', 'parent_group_id' => '19', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '2', 'sub_group_number' => '8', 'sub_sub_group_number' => '13', 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Loans (Liability)', 'sub_sub_group_name' => 'Unsecure Loans', 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '0'),
            array('id' => '23', 'sorting_number' => '22', 'name' => 'Suspense A/c', 'parent_group_id' => '11', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => '9', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Suspense', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '0'),
            array('id' => '24', 'sorting_number' => '23', 'name' => 'Expenses', 'parent_group_id' => NULL, 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '1', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '3', 'sub_group_number' => NULL, 'sub_sub_group_number' => NULL, 'main_group_name' => 'Expenses', 'sub_group_name' => NULL, 'sub_sub_group_name' => NULL, 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '0'),
            array('id' => '25', 'sorting_number' => '24', 'name' => 'Direct Expenses', 'parent_group_id' => '24', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '3', 'sub_group_number' => '10', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Expenses', 'sub_group_name' => 'Direct Expenses', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => '2022-11-27 01:26:55', 'is_global' => '0'),
            array('id' => '26', 'sorting_number' => '25', 'name' => 'Indirect Expenses', 'parent_group_id' => '24', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '3', 'sub_group_number' => '11', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Expenses', 'sub_group_name' => 'Indirect Expenses', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '0'),
            array('id' => '27', 'sorting_number' => '26', 'name' => 'Purchase Accounts', 'parent_group_id' => '24', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '3', 'sub_group_number' => '12', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Expenses', 'sub_group_name' => 'Purchase Accounts', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'dr', 'created_at' => NULL, 'updated_at' => '2022-11-27 01:22:02', 'is_global' => '0'),
            array('id' => '28', 'sorting_number' => '27', 'name' => 'Incomes', 'parent_group_id' => NULL, 'is_reserved' => '0', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '1', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '4', 'sub_group_number' => NULL, 'sub_sub_group_number' => NULL, 'main_group_name' => 'Incomes', 'sub_group_name' => NULL, 'sub_sub_group_name' => NULL, 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => NULL, 'is_global' => '0'),
            array('id' => '29', 'sorting_number' => '28', 'name' => 'Direct Incomes', 'parent_group_id' => '28', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '4', 'sub_group_number' => '13', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Incomes', 'sub_group_name' => 'Direct Incomes', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => '2022-11-27 01:27:52', 'is_global' => '0'),
            array('id' => '30', 'sorting_number' => '29', 'name' => 'Indirect Incomes', 'parent_group_id' => '28', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '4', 'sub_group_number' => '14', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Incomes', 'sub_group_name' => 'Indirect Incomes', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => '2022-11-27 01:29:13', 'is_global' => '0'),
            array('id' => '31', 'sorting_number' => '30', 'name' => 'Sales Accounts', 'parent_group_id' => '28', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '4', 'sub_group_number' => '15', 'sub_sub_group_number' => NULL, 'main_group_name' => 'Incomes', 'sub_group_name' => 'Sales Accounts', 'sub_sub_group_name' => NULL, 'default_balance_type' => 'cr', 'created_at' => NULL, 'updated_at' => '2022-11-27 02:30:24', 'is_global' => '0')
        );

        return $accountGroups;
    }
}
