<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Setups\BarcodeSetting;

class BarcodeSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $barcodeSettings = [
            array('id' => '1', 'name' => 'Sticker Print, Page/Sticker Size: 38 mm * 25 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '9', 'company_name_bold_or_regular' => '1', 'product_code_size' => '7', 'product_name_size' => '9', 'product_name_bold_or_regular' => '0', 'price_size' => '9', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '25', 'top_margin' => '8', 'left_margin' => '7', 'right_margin' => '7', 'paper_width' => '38', 'paper_height' => '25', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '1', 'stickers_in_one_sheet' => '1', 'is_default' => '1', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => '2022-12-05 10:50:05'),
            array('id' => '2', 'name' => 'Bulk - A4 Page', 'description' => NULL, 'is_continuous' => '0', 'company_name_size' => NULL, 'company_name_bold_or_regular' => '1', 'product_code_size' => NULL, 'product_name_size' => NULL, 'product_name_bold_or_regular' => '0', 'price_size' => NULL, 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '40', 'top_margin' => '0.2000', 'left_margin' => '0', 'right_margin' => '0', 'paper_width' => '8.0000', 'paper_height' => '11.0000', 'row_distance' => '0.2000', 'column_distance' => '0.2000', 'stickers_in_a_row' => '1', 'stickers_in_one_sheet' => '1', 'is_default' => '0', 'is_fixed' => '1', 'created_at' => NULL, 'updated_at' => '2022-12-05 10:50:05'),
            array('id' => '3', 'name' => 'Sticker Print, Page/Sticker Size: 30 mm * 20 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '7', 'company_name_bold_or_regular' => '1', 'product_code_size' => '7', 'product_name_size' => '7', 'product_name_bold_or_regular' => '0', 'price_size' => '8', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '25', 'top_margin' => '7', 'left_margin' => '6', 'right_margin' => '6', 'paper_width' => '30', 'paper_height' => '20', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '4', 'name' => 'Sticker Print, Page/Sticker Size: 35 mm * 25 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '8', 'company_name_bold_or_regular' => '1', 'product_code_size' => '7', 'product_name_size' => '8', 'product_name_bold_or_regular' => '0', 'price_size' => '9', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '30', 'top_margin' => '7', 'left_margin' => '7', 'right_margin' => '7', 'paper_width' => '35', 'paper_height' => '25', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '5', 'name' => 'Sticker Print, Page/Sticker Size: 45 mm * 35 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '10', 'company_name_bold_or_regular' => '1', 'product_code_size' => '9', 'product_name_size' => '11', 'product_name_bold_or_regular' => '0', 'price_size' => '10', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '35', 'top_margin' => '7', 'left_margin' => '8', 'right_margin' => '8', 'paper_width' => '45', 'paper_height' => '35', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '6', 'name' => 'Sticker Print, Page/Sticker Size: 100 mm * 150 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '18', 'company_name_bold_or_regular' => '1', 'product_code_size' => '15', 'product_name_size' => '16', 'product_name_bold_or_regular' => '0', 'price_size' => '17', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '40', 'top_margin' => '15', 'left_margin' => '15', 'right_margin' => '15', 'paper_width' => '100', 'paper_height' => '150', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '7', 'name' => 'Sticker Print, Page/Sticker Size: 100 mm * 25 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '11', 'company_name_bold_or_regular' => '1', 'product_code_size' => '10', 'product_name_size' => '10', 'product_name_bold_or_regular' => '0', 'price_size' => '11', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '30', 'top_margin' => '5', 'left_margin' => '15', 'right_margin' => '15', 'paper_width' => '100', 'paper_height' => '25', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '8', 'name' => 'Sticker Print, Page/Sticker Size: 30 mm * 10 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '6', 'company_name_bold_or_regular' => '0', 'product_code_size' => '6', 'product_name_size' => '6', 'product_name_bold_or_regular' => '0', 'price_size' => '6', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '25', 'top_margin' => '4', 'left_margin' => '6', 'right_margin' => '6', 'paper_width' => '30', 'paper_height' => '10', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '9', 'name' => 'Sticker Print, Page/Sticker Size: 30 mm * 15 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '7', 'company_name_bold_or_regular' => '1', 'product_code_size' => '6', 'product_name_size' => '7', 'product_name_bold_or_regular' => '0', 'price_size' => '6', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '20', 'top_margin' => '5', 'left_margin' => '7', 'right_margin' => '7', 'paper_width' => '30', 'paper_height' => '15', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '10', 'name' => 'Sticker Print, Page/Sticker Size: 30 mm * 40 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '8', 'company_name_bold_or_regular' => '1', 'product_code_size' => '8', 'product_name_size' => '9', 'product_name_bold_or_regular' => '0', 'price_size' => '8', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '40', 'top_margin' => '7', 'left_margin' => '7', 'right_margin' => '7', 'paper_width' => '30', 'paper_height' => '40', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '11', 'name' => 'Sticker Print, Page/Sticker Size: 32 mm * 18 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '7', 'company_name_bold_or_regular' => '1', 'product_code_size' => '7', 'product_name_size' => '7', 'product_name_bold_or_regular' => '0', 'price_size' => '7', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '22', 'top_margin' => '7', 'left_margin' => '6', 'right_margin' => '6', 'paper_width' => '32', 'paper_height' => '18', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '12', 'name' => 'Sticker Print, Page/Sticker Size: 40 mm * 10 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '6', 'company_name_bold_or_regular' => '0', 'product_code_size' => '5', 'product_name_size' => '5', 'product_name_bold_or_regular' => '0', 'price_size' => '5', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '20', 'top_margin' => '4', 'left_margin' => '5', 'right_margin' => '5', 'paper_width' => '40', 'paper_height' => '10', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '13', 'name' => 'Sticker Print, Page/Sticker Size: 50 mm * 100 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '11', 'company_name_bold_or_regular' => '1', 'product_code_size' => '11', 'product_name_size' => '12', 'product_name_bold_or_regular' => '0', 'price_size' => '13', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '50', 'top_margin' => '10', 'left_margin' => '8', 'right_margin' => '8', 'paper_width' => '50', 'paper_height' => '100', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '14', 'name' => 'Sticker Print, Page/Sticker Size: 50 mm * 25 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '9', 'company_name_bold_or_regular' => '1', 'product_code_size' => '7', 'product_name_size' => '10', 'product_name_bold_or_regular' => '0', 'price_size' => '9', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '25', 'top_margin' => '7', 'left_margin' => '7', 'right_margin' => '7', 'paper_width' => '50', 'paper_height' => '25', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '15', 'name' => 'Sticker Print, Page/Sticker Size: 50 mm * 50 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '12', 'company_name_bold_or_regular' => '1', 'product_code_size' => '10', 'product_name_size' => '11', 'product_name_bold_or_regular' => '0', 'price_size' => '10', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '35', 'top_margin' => '7', 'left_margin' => '7', 'right_margin' => '7', 'paper_width' => '50', 'paper_height' => '50', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '16', 'name' => 'Sticker Print, Page/Sticker Size: 50 mm * 75 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '12', 'company_name_bold_or_regular' => '1', 'product_code_size' => '11', 'product_name_size' => '11', 'product_name_bold_or_regular' => '0', 'price_size' => '11', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '45', 'top_margin' => '7', 'left_margin' => '7', 'right_margin' => '7', 'paper_width' => '50', 'paper_height' => '75', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '17', 'name' => 'Sticker Print, Page/Sticker Size: 55 mm * 30 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '11', 'company_name_bold_or_regular' => '1', 'product_code_size' => '9', 'product_name_size' => '10', 'product_name_bold_or_regular' => '0', 'price_size' => '10', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '30', 'top_margin' => '7', 'left_margin' => '7', 'right_margin' => '7', 'paper_width' => '55', 'paper_height' => '30', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '18', 'name' => 'Sticker Print, Page/Sticker Size: 55 mm * 35 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '11', 'company_name_bold_or_regular' => '1', 'product_code_size' => '10', 'product_name_size' => '10', 'product_name_bold_or_regular' => '0', 'price_size' => '10', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '30', 'top_margin' => '7', 'left_margin' => '7', 'right_margin' => '7', 'paper_width' => '55', 'paper_height' => '30', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL),
            array('id' => '19', 'name' => 'Sticker Print, Page/Sticker Size: 75 mm * 100 mm', 'description' => NULL, 'is_continuous' => '1', 'company_name_size' => '15', 'company_name_bold_or_regular' => '1', 'product_code_size' => '15', 'product_name_size' => '15', 'product_name_bold_or_regular' => '0', 'price_size' => '15', 'price_bold_or_regular' => '1', 'bar_width' => '100', 'bar_height' => '40', 'top_margin' => '10', 'left_margin' => '10', 'right_margin' => '10', 'paper_width' => '75', 'paper_height' => '100', 'row_distance' => '0.0000', 'column_distance' => '0.0000', 'stickers_in_a_row' => '0', 'stickers_in_one_sheet' => '0', 'is_default' => '0', 'is_fixed' => '0', 'created_at' => NULL, 'updated_at' => NULL)
        ];

        ////////////// Only for update
        // foreach ($barcodeSettings as $barcodeSetting) {

        //     $exists = DB::table()->where('id', $barcodeSetting['id'])->first();

        //     if (isset($exists)) {

        //         DB::table('barcode_settings')->insert($barcodeSetting);
        //     }
        // }

        ///////////// Only for start tenant
        BarcodeSetting::truncate();
        DB::table('barcode_settings')->insert($barcodeSettings);
    }
}
