<?php

namespace Database\Seeders;

use App\Models\GeneralSetting;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Services\CacheServiceInterface;

class GeneralSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(CacheServiceInterface $cacheService)
    {
        $generalSettings = array(
            array('key' => 'subscription__has_business', 'value' => 1, 'branch_id' => null),
            array('key' => 'subscription__branch_count', 'value' => 1, 'branch_id' => null),
            array('key' => 'subscription__is_completed_business_setup', 'value' => 0, 'branch_id' => null),
            array('key' => 'subscription__is_completed_branch_startup', 'value' => 0, 'branch_id' => null),
            array('key' => 'business_or_shop__business_name', 'value' => 'Company Name', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__address', 'value' => 'Dhaka, Bangladesh', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__phone', 'value' => 'XXXXXXXXXX', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__email', 'value' => 'company.email@provider.com', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__account_start_date', 'value' => date('d-m-Y'), 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__financial_year_start_month', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__default_profit', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__currency_id', 'value' => '2', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__currency_symbol', 'value' => '$', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__date_format', 'value' => 'd-m-Y', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__stock_accounting_method', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__time_format', 'value' => '12', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__business_logo', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'business_or_shop__timezone', 'value' => 'Asia/Dhaka', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'system__theme_color', 'value' => 'dark-theme', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'system__datatables_page_entry', 'value' => '50', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_enabled_multiple_pay', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_enabled_draft', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_enabled_quotation', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_enabled_suspend', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_enabled_discount', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_enabled_order_tax', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_enabled_credit_full_sale', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_enabled_hold_invoice', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'product__product_code_prefix', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'product__default_unit_id', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'product__is_enable_brands', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'product__is_enable_categories', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'product__is_enable_sub_categories', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'product__is_enable_price_tax', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'product__is_enable_warranty', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'add_sale__default_sale_discount', 'value' => '0.00', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'add_sale__default_price_group_id', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_disable_draft', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_disable_quotation', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_disable_delivery_note', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_disable_hold_invoice', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_disable_multiple_pay', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_show_recent_transactions', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_disable_discount', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_disable_order_tax', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_show_credit_sale_button', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__is_show_partial_sale_button', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'purchase__is_edit_pro_price', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'purchase__is_enable_status', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'purchase__is_enable_lot_no', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'dashboard__view_stock_expiry_alert_for', 'value' => '31', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__sales_invoice_prefix', 'value' => 'SI', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__quotation_prefix', 'value' => 'Q', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__sales_order_prefix', 'value' => 'SO', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__sales_return_prefix', 'value' => 'SR', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__payment_voucher_prefix', 'value' => 'PV', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__receipt_voucher_prefix', 'value' => 'RV', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__expense_voucher_prefix', 'value' => 'EX', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__contra_voucher_prefix', 'value' => 'CO', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__purchase_invoice_prefix', 'value' => 'PI', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__purchase_order_prefix', 'value' => 'PO', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__purchase_return_prefix', 'value' => 'PR', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__stock_adjustment_prefix', 'value' => 'SA', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__payroll_voucher_prefix', 'value' => 'PRL', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__payroll_payment_voucher_prefix', 'value' => 'PRLP', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__stock_issue_voucher_prefix', 'value' => 'STI', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__job_card_no_prefix', 'value' => 'JOB', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__supplier_id', 'value' => 'S', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'prefix__customer_id', 'value' => 'C', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'modules__purchases', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'modules__add_sale', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'modules__pos', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'modules__transfer_stock', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'modules__stock_adjustments', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'modules__accounting', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'modules__contacts', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'modules__hrms', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'modules__manage_task', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'modules__manufacturing', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'modules__service', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'reward_point_settings__enable_cus_point', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'reward_point_settings__point_display_name', 'value' => 'Reward Point', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'reward_point_settings__amount_for_unit_rp', 'value' => '10', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'reward_point_settings__min_order_total_for_rp', 'value' => '100', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'reward_point_settings__max_rp_per_order', 'value' => '', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'reward_point_settings__redeem_amount_per_unit_rp', 'value' => '0.10', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'reward_point_settings__min_order_total_for_redeem', 'value' => '', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'reward_point_settings__min_redeem_point', 'value' => '', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'reward_point_settings__max_redeem_point', 'value' => '', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'send_email__send_invoice_via_email', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'send_email__send_notification_via_email', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'send_email__customer_due_reminder_via_email', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'send_email__user_forget_password_via_email', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'send_email__coupon_offer_via_email', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'send_sms__send_invoice_via_sms', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'send_sms__send_notification_via_sms', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'send_sms__customer_due_reminder_via_sms', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'add_sale__default_tax_ac_id', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'pos__default_tax_ac_id', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'manufacturing__production_voucher_prefix', 'value' => 'MF', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'manufacturing__is_edit_ingredients_qty_in_production', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'manufacturing__is_update_product_cost_and_price_in_production', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'invoice_layout__add_sale_invoice_layout_id', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'invoice_layout__pos_sale_invoice_layout_id', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__add_sale_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__pos_sale_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__quotation_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__sales_order_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__draft_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__sales_return_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__purchase_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__purchase_order_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__purchase_return_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__transfer_stock_voucher_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__stock_adjustment_voucher_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__receipt_voucher_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__payment_voucher_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__expense_voucher_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__contra_voucher_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__payroll_voucher_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__payroll_payment_voucher_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__bom_voucher_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'print_page_size__production_voucher_page_size', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings__default_status_id', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings__default_checklist', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings__product_configuration', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings__default_problems_report', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings__product_condition', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings__terms_and_condition', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings__custom_field_1_label', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings__custom_field_2_label', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings__custom_field_3_label', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings__custom_field_4_label', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings__custom_field_5_label', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__show_customer_info', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__customer_label_name', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__show_contact_id', 'value' => 0, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__customer_id_label_name', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__show_customer_tax_no', 'value' => 0, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__customer_tax_no_label_name', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__show_custom_field_1', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__show_custom_field_2', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__show_custom_field_3', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__show_custom_field_4', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__show_custom_field_5', 'value' => '0', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__label_width', 'value' => '75', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__label_height', 'value' => '55', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__customer_name_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__customer_address_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__customer_phone_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__customer_alt_phone_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__customer_email_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__sales_person_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__barcode_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__status_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__due_date_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__technician_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__problems_in_label_in_label', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__job_card_no_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__serial_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__model_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__location_in_label', 'value' => NULL, 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__password_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL),
            array('key' => 'service_settings_pdf_label__problems_in_label', 'value' => '1', 'branch_id' => NULL, 'parent_branch_id' => NULL)
        );

        $cacheService->forgetGeneralSettingsCache();
        GeneralSetting::truncate();
        // $settings = $this->getSettings();
        DB::table('general_settings')->insert($generalSettings);
        // foreach ($settings as $setting) {
        //     GeneralSetting::insert([
        //         'key' => $setting['key'],
        //         'value' => $setting['value'],
        //         'branch_id' => $setting['branch_id'],
        //     ]);
        // }
    }
}
