<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = array(
            array('type' => '1','name' => 'Pen','product_code' => '2195937','category_id' => NULL,'parent_category_id' => NULL,'brand_id' => NULL,'unit_id' => '16','tax_id' => NULL,'tax_type' => '1','warranty_id' => NULL,'product_cost' => '56.00','product_cost_with_tax' => '56.00','profit' => '87.00','product_price' => '104.72','offer_price' => '0.00','is_manage_stock' => '1','quantity' => '0.00','combo_price' => '0.00','alert_quantity' => '359','is_featured' => '0','is_combo' => '0','is_variant' => '0','is_show_in_ecom' => '0','is_show_emi_on_pos' => '1','is_for_sale' => '0','attachment' => NULL,'thumbnail_photo' => 'default.png','expire_date' => NULL,'product_details' => NULL,'is_purchased' => '0','barcode_type' => 'CODE128','weight' => 'Ipsa blanditiis vol','product_condition' => 'New','status' => '1','number_of_sale' => '0.00','total_transfered' => '0.00','total_adjusted' => '0.00','custom_field_1' => 'Quia voluptatum veni','custom_field_2' => 'Doloribus molestiae','custom_field_3' => 'Assumenda rerum veli','created_at' => '2023-01-08 12:50:42','updated_at' => '2023-01-08 12:50:42'),
            array('type' => '1','name' => 'Pencil','product_code' => 'Sed','category_id' => '121','parent_category_id' => NULL,'brand_id' => NULL,'unit_id' => '16','tax_id' => NULL,'tax_type' => '1','warranty_id' => NULL,'product_cost' => '71.00','product_cost_with_tax' => '71.00','profit' => '96.00','product_price' => '139.16','offer_price' => '0.00','is_manage_stock' => '1','quantity' => '0.00','combo_price' => '0.00','alert_quantity' => '860','is_featured' => '0','is_combo' => '0','is_variant' => '0','is_show_in_ecom' => '1','is_show_emi_on_pos' => '0','is_for_sale' => '1','attachment' => NULL,'thumbnail_photo' => 'default.png','expire_date' => NULL,'product_details' => NULL,'is_purchased' => '0','barcode_type' => 'CODE39','weight' => 'Rerum dolorum ut mag','product_condition' => 'New','status' => '1','number_of_sale' => '0.00','total_transfered' => '0.00','total_adjusted' => '0.00','custom_field_1' => 'Aliquam est ipsam d','custom_field_2' => 'Animi facere enim f','custom_field_3' => 'Sit quod at quam aut','created_at' => '2023-01-08 12:51:10','updated_at' => '2023-01-08 12:51:10'),
            array('type' => '1','name' => 'Book','product_code' => 'Ver','category_id' => '113','parent_category_id' => NULL,'brand_id' => NULL,'unit_id' => '16','tax_id' => NULL,'tax_type' => '1','warranty_id' => NULL,'product_cost' => '23.00','product_cost_with_tax' => '23.00','profit' => '75.00','product_price' => '40.25','offer_price' => '0.00','is_manage_stock' => '0','quantity' => '0.00','combo_price' => '0.00','alert_quantity' => '99','is_featured' => '0','is_combo' => '0','is_variant' => '1','is_show_in_ecom' => '1','is_show_emi_on_pos' => '0','is_for_sale' => '1','attachment' => NULL,'thumbnail_photo' => '63ba687722f37.jpg','expire_date' => NULL,'product_details' => NULL,'is_purchased' => '0','barcode_type' => 'UPC','weight' => 'Maxime suscipit eius','product_condition' => 'New','status' => '1','number_of_sale' => '0.00','total_transfered' => '0.00','total_adjusted' => '0.00','custom_field_1' => 'Officiis voluptate s','custom_field_2' => 'Consequatur earum es','custom_field_3' => 'Dolore est et commod','created_at' => '2023-01-08 12:53:43','updated_at' => '2023-01-08 12:53:43'),
            array('type' => '1','name' => 'KeyBoard','product_code' => 'seq','category_id' => '122','parent_category_id' => NULL,'brand_id' => NULL,'unit_id' => '16','tax_id' => NULL,'tax_type' => '1','warranty_id' => NULL,'product_cost' => '77.00','product_cost_with_tax' => '77.00','profit' => '8.00','product_price' => '83.16','offer_price' => '0.00','is_manage_stock' => '0','quantity' => '0.00','combo_price' => '0.00','alert_quantity' => '231','is_featured' => '0','is_combo' => '0','is_variant' => '1','is_show_in_ecom' => '1','is_show_emi_on_pos' => '0','is_for_sale' => '1','attachment' => NULL,'thumbnail_photo' => 'default.png','expire_date' => NULL,'product_details' => NULL,'is_purchased' => '0','barcode_type' => 'EAN13','weight' => 'Qui nostrud itaque n','product_condition' => 'New','status' => '1','number_of_sale' => '0.00','total_transfered' => '0.00','total_adjusted' => '0.00','custom_field_1' => 'Voluptatem Consequu','custom_field_2' => 'Dolor hic ducimus d','custom_field_3' => 'Assumenda recusandae','created_at' => '2023-01-08 15:22:06','updated_at' => '2023-01-08 15:22:06'),
            array('type' => '1','name' => 'Mouse','product_code' => 'exercitation','category_id' => '126','parent_category_id' => NULL,'brand_id' => NULL,'unit_id' => '16','tax_id' => NULL,'tax_type' => '1','warranty_id' => NULL,'product_cost' => '68.00','product_cost_with_tax' => '68.00','profit' => '7.00','product_price' => '72.76','offer_price' => '0.00','is_manage_stock' => '1','quantity' => '0.00','combo_price' => '0.00','alert_quantity' => '234','is_featured' => '0','is_combo' => '0','is_variant' => '0','is_show_in_ecom' => '1','is_show_emi_on_pos' => '0','is_for_sale' => '1','attachment' => NULL,'thumbnail_photo' => '63ba8b7dc9d87.jpg','expire_date' => NULL,'product_details' => NULL,'is_purchased' => '0','barcode_type' => 'EAN13','weight' => 'Dolores voluptatem d','product_condition' => 'New','status' => '1','number_of_sale' => '0.00','total_transfered' => '0.00','total_adjusted' => '0.00','custom_field_1' => 'Tempor aut molestias','custom_field_2' => 'Aliquid impedit imp','custom_field_3' => 'Quia qui exercitatio','created_at' => '2023-01-08 15:23:09','updated_at' => '2023-01-08 15:23:09')
          );
          DB::table('products')->insert($products);
    }
}
