<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = array(
            array('type' => '1','name' => 'Cap','product_code' => 'Animi inventore iru','category_id' => NULL,'parent_category_id' => NULL,'brand_id' => NULL,'unit_id' => '1','tax_id' => NULL,'tax_type' => '1','warranty_id' => NULL,'product_cost' => '140.00','product_cost_with_tax' => '140.00','profit' => '13.00','product_price' => '158.20','offer_price' => '0.00','is_manage_stock' => '0','quantity' => '0.00','combo_price' => '0.00','alert_quantity' => '14','is_featured' => '0','is_combo' => '0','is_variant' => '0','is_show_in_ecom' => '0','is_show_emi_on_pos' => '0','is_for_sale' => '0','attachment' => NULL,'thumbnail_photo' => '63bbb8c36a2aa.png','expire_date' => NULL,'product_details' => NULL,'is_purchased' => '0','barcode_type' => 'UPC','weight' => NULL,'product_condition' => 'New','status' => '1','number_of_sale' => '0.00','total_transfered' => '0.00','total_adjusted' => '0.00','custom_field_1' => NULL,'custom_field_2' => NULL,'custom_field_3' => NULL,'created_at' => '2023-01-09 12:48:35','updated_at' => '2023-01-10 12:59:38'),
            array('type' => '1','name' => 'Pen','product_code' => '2523866','category_id' => NULL,'parent_category_id' => NULL,'brand_id' => NULL,'unit_id' => '3','tax_id' => NULL,'tax_type' => '1','warranty_id' => NULL,'product_cost' => '1000.00','product_cost_with_tax' => '1000.00','profit' => '8.00','product_price' => '1080.00','offer_price' => '0.00','is_manage_stock' => '1','quantity' => '9999991.00','combo_price' => '0.00','alert_quantity' => '10','is_featured' => '0','is_combo' => '0','is_variant' => '1','is_show_in_ecom' => '0','is_show_emi_on_pos' => '0','is_for_sale' => '1','attachment' => NULL,'thumbnail_photo' => '63bbb917d417c.jpg','expire_date' => NULL,'product_details' => NULL,'is_purchased' => '1','barcode_type' => 'CODE128','weight' => NULL,'product_condition' => 'New','status' => '1','number_of_sale' => '10.00','total_transfered' => '0.00','total_adjusted' => '0.00','custom_field_1' => NULL,'custom_field_2' => NULL,'custom_field_3' => NULL,'created_at' => '2023-01-09 12:49:59','updated_at' => '2023-01-09 16:15:08'),
            array('type' => '1','name' => 'Keyboard','product_code' => '8386465','category_id' => '2','parent_category_id' => NULL,'brand_id' => '1','unit_id' => '3','tax_id' => NULL,'tax_type' => '1','warranty_id' => NULL,'product_cost' => '1500.00','product_cost_with_tax' => '1500.00','profit' => '0.00','product_price' => '1575.00','offer_price' => '0.00','is_manage_stock' => '1','quantity' => '100000000.00','combo_price' => '0.00','alert_quantity' => '10','is_featured' => '0','is_combo' => '0','is_variant' => '0','is_show_in_ecom' => '0','is_show_emi_on_pos' => '0','is_for_sale' => '1','attachment' => NULL,'thumbnail_photo' => '63bbba5ae4a5e.jpg','expire_date' => NULL,'product_details' => NULL,'is_purchased' => '0','barcode_type' => 'CODE128','weight' => NULL,'product_condition' => 'New','status' => '1','number_of_sale' => '0.00','total_transfered' => '0.00','total_adjusted' => '0.00','custom_field_1' => NULL,'custom_field_2' => NULL,'custom_field_3' => NULL,'created_at' => '2023-01-09 12:54:25','updated_at' => '2023-01-10 12:59:36'),
            array('type' => '1','name' => 'Book','product_code' => '6214139','category_id' => '2','parent_category_id' => NULL,'brand_id' => '1','unit_id' => '3','tax_id' => NULL,'tax_type' => '1','warranty_id' => NULL,'product_cost' => '1000.00','product_cost_with_tax' => '1000.00','profit' => '9.00','product_price' => '1090.00','offer_price' => '0.00','is_manage_stock' => '1','quantity' => '100000000000000.00','combo_price' => '0.00','alert_quantity' => '10','is_featured' => '0','is_combo' => '0','is_variant' => '0','is_show_in_ecom' => '0','is_show_emi_on_pos' => '0','is_for_sale' => '1','attachment' => NULL,'thumbnail_photo' => '63bbf2cfc9e44.jpg','expire_date' => NULL,'product_details' => NULL,'is_purchased' => '0','barcode_type' => 'EAN13','weight' => NULL,'product_condition' => 'New','status' => '1','number_of_sale' => '0.00','total_transfered' => '0.00','total_adjusted' => '0.00','custom_field_1' => NULL,'custom_field_2' => NULL,'custom_field_3' => NULL,'created_at' => '2023-01-09 16:56:15','updated_at' => '2023-01-09 16:57:28'),
            array('type' => '1','name' => 'Cup','product_code' => 'Nostrum dolor volupt','category_id' => '1','parent_category_id' => NULL,'brand_id' => '2','unit_id' => '7','tax_id' => NULL,'tax_type' => '1','warranty_id' => '1','product_cost' => '43.00','product_cost_with_tax' => '43.00','profit' => '20.00','product_price' => '51.60','offer_price' => '0.00','is_manage_stock' => '0','quantity' => '0.00','combo_price' => '0.00','alert_quantity' => '936','is_featured' => '0','is_combo' => '0','is_variant' => '1','is_show_in_ecom' => '1','is_show_emi_on_pos' => '0','is_for_sale' => '1','attachment' => NULL,'thumbnail_photo' => 'default.png','expire_date' => NULL,'product_details' => NULL,'is_purchased' => '1','barcode_type' => 'UPC','weight' => 'Natus est ea dolor s','product_condition' => 'New','status' => '1','number_of_sale' => '0.00','total_transfered' => '0.00','total_adjusted' => '0.00','custom_field_1' => 'Ratione quo voluptas','custom_field_2' => 'Commodi veniam repr','custom_field_3' => 'Minim magnam quod at','created_at' => '2023-01-10 12:33:47','updated_at' => '2023-01-10 12:36:45')
          );
          DB::table('products')->insert($products);
    }
}
