<?php

namespace App\Services\Setups;

use App\Models\Accounts\AccountGroup;
use App\Models\Branch;

class BranchService
{
    public function addBranch($request) : object
    {
        $addBranch = new Branch();
        $addBranch->name = $request->name;
        $addBranch->branch_code = $request->code;
        $addBranch->phone = $request->phone;
        $addBranch->city = $request->city;
        $addBranch->state = $request->state;
        $addBranch->zip_code = $request->zip_code;
        $addBranch->country = $request->country;
        $addBranch->alternate_phone_number = $request->alternate_phone_number;
        $addBranch->email = $request->email;
        $addBranch->website = $request->website;
        $addBranch->purchase_permission = $request->purchase_permission;

        $branchLogoName = '';
        if ($request->hasFile('logo')) {

            $branchLogo = $request->file('logo');
            $branchLogoName = uniqid().'-'.'.'.$branchLogo->getClientOriginalExtension();
            $branchLogo->move(public_path('uploads/branch_logo/'), $branchLogoName);

            $addBranch->logo = $branchLogoName;
        }

        $addBranch->save();
    }

    public function addBranchDefaultAccountGroups(int $branchId): void
    {
        $account_groups = [
            ['id' => '1', 'sorting_number' => '0', 'branch_id' => $branchId, 'name' => 'Assets', 'parent_group_id' => null, 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '1', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '1', 'sub_group_number' => null, 'sub_sub_group_number' => null, 'main_group_name' => 'Assets', 'sub_group_name' => null, 'sub_sub_group_name' => null, 'default_balance_type' => 'dr', 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '2', 'sorting_number' => '1', 'branch_id' => $branchId, 'name' => 'Current Assets', 'parent_group_id' => '1', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => null, 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => null, 'default_balance_type' => 'dr', 'created_at' => null, 'updated_at' => '2022-11-27 21:40:53', 'is_global' => '0'],
            ['id' => '4', 'sorting_number' => '2', 'branch_id' => $branchId, 'name' => 'Cash-In-Hand', 'parent_group_id' => '2', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '1', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => '2', 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => 'Cash-In-Hand', 'default_balance_type' => 'dr', 'created_at' => null, 'updated_at' => '2022-11-28 01:59:29', 'is_global' => '0'],
            ['id' => '5', 'sorting_number' => '4', 'branch_id' => $branchId, 'name' => 'Deposits (Asset)', 'parent_group_id' => '2', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => '3', 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => 'Deposits (Asset)', 'default_balance_type' => 'dr', 'created_at' => null, 'updated_at' => '2022-11-27 02:29:03', 'is_global' => '0'],
            ['id' => '6', 'sorting_number' => '5', 'branch_id' => $branchId, 'name' => 'Loan & Advance (Asset)', 'parent_group_id' => '2', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => '4', 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => 'Loan & Advance (Asset)', 'default_balance_type' => 'dr', 'created_at' => null, 'updated_at' => '2022-11-27 01:30:20', 'is_global' => '0'],
            ['id' => '7', 'sorting_number' => '6', 'branch_id' => $branchId, 'name' => 'Stock-In-Hand', 'parent_group_id' => '2', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => '5', 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => 'Stock-In-Hand', 'default_balance_type' => 'dr', 'created_at' => null, 'updated_at' => '2022-11-27 02:13:12', 'is_global' => '0'],
            ['id' => '8', 'sorting_number' => '7', 'branch_id' => $branchId, 'name' => 'Account Receivable', 'parent_group_id' => '2', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '1', 'sub_group_number' => '1', 'sub_sub_group_number' => '6', 'main_group_name' => 'Assets', 'sub_group_name' => 'Current Assets', 'sub_sub_group_name' => 'Sundry Debtors', 'default_balance_type' => 'dr', 'created_at' => null, 'updated_at' => '2023-01-04 08:47:14', 'is_global' => '0'],
            ['id' => '9', 'sorting_number' => '8', 'branch_id' => $branchId, 'name' => 'Fixed Assets', 'parent_group_id' => '1', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '1', 'sub_group_number' => '2', 'sub_sub_group_number' => null, 'main_group_name' => 'Assets', 'sub_group_name' => 'Fixed Assets', 'sub_sub_group_name' => null, 'default_balance_type' => 'dr', 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '10', 'sorting_number' => '9', 'branch_id' => $branchId, 'name' => 'Investments', 'parent_group_id' => '1', 'is_reserved' => '0', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '1', 'sub_group_number' => '3', 'sub_sub_group_number' => null, 'main_group_name' => 'Assets', 'sub_group_name' => 'Investments', 'sub_sub_group_name' => null, 'default_balance_type' => 'dr', 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '11', 'sorting_number' => '10', 'branch_id' => $branchId, 'name' => 'Liabilities', 'parent_group_id' => null, 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '1', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => null, 'sub_sub_group_number' => null, 'main_group_name' => 'Liabilities', 'sub_group_name' => null, 'sub_sub_group_name' => null, 'default_balance_type' => 'cr', 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '12', 'sorting_number' => '11', 'branch_id' => $branchId, 'name' => 'Branch / Divisions', 'parent_group_id' => '11', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => '5', 'sub_sub_group_number' => null, 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Branch / Divisions', 'sub_sub_group_name' => null, 'default_balance_type' => 'cr', 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '13', 'sorting_number' => '12', 'branch_id' => $branchId, 'name' => 'Capital Account', 'parent_group_id' => '11', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => '6', 'sub_sub_group_number' => null, 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Capital Account', 'sub_sub_group_name' => null, 'default_balance_type' => 'cr', 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '14', 'sorting_number' => '13', 'branch_id' => $branchId, 'name' => 'Reserves / Surplus', 'parent_group_id' => '13', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => '6', 'sub_sub_group_number' => '7', 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Capital Account', 'sub_sub_group_name' => null, 'default_balance_type' => 'cr', 'created_at' => null, 'updated_at' => '2022-11-27 01:33:20', 'is_global' => '0'],
            ['id' => '15', 'sorting_number' => '14', 'branch_id' => $branchId, 'name' => 'Current Liabilities', 'parent_group_id' => '11', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => '7', 'sub_sub_group_number' => null, 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Current Liabilities', 'sub_sub_group_name' => null, 'default_balance_type' => 'cr', 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '16', 'sorting_number' => '15', 'branch_id' => $branchId, 'name' => 'Duties & Taxes', 'parent_group_id' => '15', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '1', 'is_default_tax_calculator' => '1', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '2', 'sub_group_number' => '7', 'sub_sub_group_number' => '8', 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Current Liabilities', 'sub_sub_group_name' => 'Duties & Taxes', 'default_balance_type' => 'cr', 'created_at' => null, 'updated_at' => '2022-11-27 02:17:19', 'is_global' => '0'],
            ['id' => '17', 'sorting_number' => '16', 'branch_id' => $branchId, 'name' => 'Provisions', 'parent_group_id' => '15', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '2', 'sub_group_number' => '7', 'sub_sub_group_number' => '9', 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Current Liabilities', 'sub_sub_group_name' => 'Provisions', 'default_balance_type' => 'cr', 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '18', 'sorting_number' => '17', 'branch_id' => $branchId, 'name' => 'Account Payable', 'parent_group_id' => '15', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '2', 'sub_group_number' => '7', 'sub_sub_group_number' => '10', 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Current Liabilities', 'sub_sub_group_name' => 'Sundry Creditors', 'default_balance_type' => 'cr', 'created_at' => null, 'updated_at' => '2023-01-04 08:47:27', 'is_global' => '1'],
            ['id' => '19', 'sorting_number' => '18', 'branch_id' => $branchId, 'name' => 'Loans (Liability)', 'parent_group_id' => '11', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => '8', 'sub_sub_group_number' => null, 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Loans (Liability)', 'sub_sub_group_name' => null, 'default_balance_type' => 'cr', 'created_at' => null, 'updated_at' => '2022-11-27 02:30:51', 'is_global' => '0'],
            ['id' => '21', 'sorting_number' => '20', 'branch_id' => $branchId, 'name' => 'Secure Loans', 'parent_group_id' => '19', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '2', 'sub_group_number' => '8', 'sub_sub_group_number' => '12', 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Loans (Liability)', 'sub_sub_group_name' => 'Secure Loans', 'default_balance_type' => 'cr', 'created_at' => null, 'updated_at' => '2022-11-27 21:41:04', 'is_global' => '0'],
            ['id' => '22', 'sorting_number' => '21', 'branch_id' => $branchId, 'name' => 'Unsecure Loans', 'parent_group_id' => '19', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '1', 'is_parent_sub_sub_group' => '1', 'main_group_number' => '2', 'sub_group_number' => '8', 'sub_sub_group_number' => '13', 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Loans (Liability)', 'sub_sub_group_name' => 'Unsecure Loans', 'default_balance_type' => 'cr', 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '23', 'sorting_number' => '22', 'branch_id' => $branchId, 'name' => 'Suspense A/c', 'parent_group_id' => '11', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '2', 'sub_group_number' => '9', 'sub_sub_group_number' => null, 'main_group_name' => 'Liabilities', 'sub_group_name' => 'Suspense', 'sub_sub_group_name' => null, 'default_balance_type' => 'cr', 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '24', 'sorting_number' => '23', 'branch_id' => $branchId, 'name' => 'Expenses', 'parent_group_id' => null, 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '1', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '3', 'sub_group_number' => null, 'sub_sub_group_number' => null, 'main_group_name' => 'Expenses', 'sub_group_name' => null, 'sub_sub_group_name' => null, 'default_balance_type' => 'dr', 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '25', 'sorting_number' => '24', 'branch_id' => $branchId, 'name' => 'Direct Expenses', 'parent_group_id' => '24', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '3', 'sub_group_number' => '10', 'sub_sub_group_number' => null, 'main_group_name' => 'Expenses', 'sub_group_name' => 'Direct Expenses', 'sub_sub_group_name' => null, 'default_balance_type' => 'dr', 'created_at' => null, 'updated_at' => '2022-11-27 01:26:55', 'is_global' => '0'],
            ['id' => '26', 'sorting_number' => '25', 'branch_id' => $branchId, 'name' => 'Indirect Expenses', 'parent_group_id' => '24', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '3', 'sub_group_number' => '11', 'sub_sub_group_number' => null, 'main_group_name' => 'Expenses', 'sub_group_name' => 'Indirect Expenses', 'sub_sub_group_name' => 'dr', 'default_balance_type' => null, 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '27', 'sorting_number' => '26', 'branch_id' => $branchId, 'name' => 'Purchase Accounts', 'parent_group_id' => '24', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '3', 'sub_group_number' => '12', 'sub_sub_group_number' => null, 'main_group_name' => 'Expenses', 'sub_group_name' => 'Purchase Accounts', 'sub_sub_group_name' => 'dr', 'default_balance_type' => null, 'created_at' => null, 'updated_at' => '2022-11-27 01:22:02', 'is_global' => '0'],
            ['id' => '28', 'sorting_number' => '27', 'branch_id' => $branchId, 'name' => 'Incomes', 'parent_group_id' => null, 'is_reserved' => '0', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '1', 'is_sub_group' => '0', 'is_parent_sub_group' => '0', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '4', 'sub_group_number' => null, 'sub_sub_group_number' => null, 'main_group_name' => 'Incomes', 'sub_group_name' => null, 'sub_sub_group_name' => 'cr', 'default_balance_type' => null, 'created_at' => null, 'updated_at' => null, 'is_global' => '0'],
            ['id' => '29', 'sorting_number' => '28', 'branch_id' => $branchId, 'name' => 'Direct Incomes', 'parent_group_id' => '28', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '4', 'sub_group_number' => '13', 'sub_sub_group_number' => null, 'main_group_name' => 'Incomes', 'sub_group_name' => 'Direct Incomes', 'sub_sub_group_name' => 'cr', 'default_balance_type' => null, 'created_at' => null, 'updated_at' => '2022-11-27 01:27:52', 'is_global' => '0'],
            ['id' => '30', 'sorting_number' => '29', 'branch_id' => $branchId, 'name' => 'Indirect Incomes', 'parent_group_id' => '28', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '4', 'sub_group_number' => '14', 'sub_sub_group_number' => null, 'main_group_name' => 'Incomes', 'sub_group_name' => 'Indirect Incomes', 'sub_sub_group_name' => 'cr', 'default_balance_type' => null, 'created_at' => null, 'updated_at' => '2022-11-27 01:29:13', 'is_global' => '0'],
            ['id' => '31', 'sorting_number' => '30', 'branch_id' => $branchId, 'name' => 'Sales Accounts', 'parent_group_id' => '28', 'is_reserved' => '1', 'is_allowed_bank_details' => '0', 'is_bank_or_cash_ac' => '0', 'is_fixed_tax_calculator' => '0', 'is_default_tax_calculator' => '0', 'is_main_group' => '0', 'is_sub_group' => '1', 'is_parent_sub_group' => '1', 'is_sub_sub_group' => '0', 'is_parent_sub_sub_group' => '0', 'main_group_number' => '4', 'sub_group_number' => '15', 'sub_sub_group_number' => null, 'main_group_name' => 'Incomes', 'sub_group_name' => 'Sales Accounts', 'sub_sub_group_name' => 'cr', 'default_balance_type' => null, 'created_at' => null, 'updated_at' => '2022-11-27 02:30:24', 'is_global' => '0'],
        ];

        array_walk($account_groups, function (&$v) {
            unset($v['id']);
        });

        AccountGroup::insert($account_groups);
    }

    public function addBranchDefaultAccounts(int $branchId): void
    {
        $cashInHand = AccountGroup::where('account_groups')->where('sub_sub_group_number', 2)->where('branch_id', $branchId)->first();
        $directExpenseGroup = AccountGroup::where('account_groups')->where('sub_group_number', 10)->where('branch_id', $branchId)->first();
        $directIncomeGroup = AccountGroup::where('account_groups')->where('sub_group_number', 13)->where('branch_id', $branchId)->first();
        $salesAccountGroup = AccountGroup::where('account_groups')->where('sub_group_number', 15)->where('branch_id', $branchId)->first();
        $purchaseAccountGroup = AccountGroup::where('account_groups')->where('sub_group_number', 12)->where('branch_id', $branchId)->first();
        $suspenseAccountGroup = AccountGroup::where('account_groups')->where('sub_group_number', 9)->where('branch_id', $branchId)->first();
        $capitalAccountGroup = AccountGroup::where('account_groups')->where('sub_group_number', 6)->where('branch_id', $branchId)->first();
        $dutiesAndTaxAccountGroup = AccountGroup::where('account_groups')->where('sub_sub_group_number', 8)->where('branch_id', $branchId)->first();

        $accounts = [
            ['account_group_id' => $cashInHand->id, 'name' => 'Cash', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '0.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'debit', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => '1', 'is_main_capital_account' => null, 'is_main_pl_account' => null, 'created_at' => '2023-08-04 17:33:01', 'updated_at' => '2023-08-04 17:33:01', 'branch_id' => $branchId],
            ['account_group_id' => $salesAccountGroup->id, 'name' => 'Sales Account Ledger', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '0.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'dr', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => '1', 'is_main_capital_account' => null, 'is_main_pl_account' => null, 'created_at' => '2023-08-06 12:02:13', 'updated_at' => '2023-08-06 12:02:13', 'branch_id' => $branchId],
            ['account_group_id' => $dutiesAndTaxAccountGroup->id, 'name' => 'Tax@5%', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '5.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'dr', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => null, 'is_main_capital_account' => null, 'is_main_pl_account' => null, 'created_at' => '2023-08-06 16:59:55', 'updated_at' => '2023-08-06 16:59:55', 'branch_id' => $branchId],
            ['account_group_id' => $dutiesAndTaxAccountGroup->id, 'name' => 'Tax@8%', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '8.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'dr', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => null, 'is_main_capital_account' => null, 'is_main_pl_account' => null, 'created_at' => '2023-08-06 17:00:18', 'updated_at' => '2023-08-06 17:00:18', 'branch_id' => $branchId],
            ['account_group_id' => $purchaseAccountGroup->id, 'name' => 'Purchase Ledger Account', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '0.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'dr', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => null, 'is_main_capital_account' => null, 'is_main_pl_account' => null, 'created_at' => '2023-08-08 18:09:48', 'updated_at' => '2023-08-08 18:09:48', 'branch_id' => $branchId],
            ['account_group_id' => $directExpenseGroup->id, 'name' => 'Net Bill', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '0.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'dr', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => null, 'is_main_capital_account' => null, 'is_main_pl_account' => null, 'created_at' => '2023-08-08 18:10:36', 'updated_at' => '2023-08-08 18:10:36', 'branch_id' => $branchId],
            ['account_group_id' => $directExpenseGroup->id, 'name' => 'Electricity Bill', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '0.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'dr', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => null, 'is_main_capital_account' => null, 'is_main_pl_account' => null, 'created_at' => '2023-08-08 18:10:53', 'updated_at' => '2023-08-08 18:10:53', 'branch_id' => $branchId],
            ['account_group_id' => $directExpenseGroup->id, 'name' => 'Snacks Bill', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '0.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'dr', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => null, 'is_main_capital_account' => null, 'is_main_pl_account' => null, 'created_at' => '2023-08-08 18:11:16', 'updated_at' => '2023-08-08 18:11:16', 'branch_id' => $branchId],
            ['account_group_id' => $directExpenseGroup->id, 'name' => 'Roll Pages', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '0.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'dr', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => null, 'is_main_capital_account' => null, 'is_main_pl_account' => null, 'created_at' => '2023-08-08 18:11:59', 'updated_at' => '2023-08-08 18:11:59', 'branch_id' => $branchId],
            ['account_group_id' => $directIncomeGroup->id, 'name' => 'Sale Damage Goods', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '0.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'dr', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => null, 'is_main_capital_account' => null, 'is_main_pl_account' => null, 'created_at' => '2023-08-08 18:12:33', 'updated_at' => '2023-08-08 18:12:33', 'branch_id' => $branchId],
            ['account_group_id' => $directExpenseGroup->id, 'name' => 'Lost/Damage Stock', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '0.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'dr', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => null, 'is_main_capital_account' => null, 'is_main_pl_account' => null, 'created_at' => '2023-08-08 18:13:13', 'updated_at' => '2023-08-08 18:13:13', 'branch_id' => $branchId],
            ['account_group_id' => $suspenseAccountGroup->id, 'name' => 'Profit Loss Account', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '0.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'dr', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => null, 'is_main_capital_account' => null, 'is_main_pl_account' => '1', 'created_at' => '2023-08-08 18:13:57', 'updated_at' => '2023-08-08 18:13:57', 'branch_id' => $branchId],
            ['account_group_id' => $capitalAccountGroup->id, 'name' => 'Capital Account', 'phone' => null, 'contact_id' => null, 'address' => null, 'account_number' => null, 'bank_id' => null, 'bank_branch' => null, 'bank_address' => null, 'tax_percent' => '0.00', 'bank_code' => null, 'swift_code' => null, 'opening_balance' => '0.00', 'opening_balance_type' => 'dr', 'remark' => null, 'status' => '1', 'created_by_id' => '1', 'is_fixed' => null, 'is_main_capital_account' => '1', 'is_main_pl_account' => null, 'created_at' => '2023-08-08 18:14:40', 'updated_at' => '2023-08-08 18:14:40', 'branch_id' => $branchId],
        ];

        Account::insert($accounts);
    }

    public function branches(array $with = null)
    {
        $query = Branch::query();

        if (isset($with)) {

            $query->with($with);
        }

        return $query;
    }


    public function singleCashCounter(int $id, array $with = null)
    {
        $query = Branch::query();

        if (isset($with)) {

            $query->with($with);
        }

        return $query->where('id', $id)->first();
    }

    public function addBranchOpeningUser($request, $branchId)
    {
        $addUser = new User();
        $addUser->name = $request->first_name;
        $addUser->last_name = $request->last_name;
        $addUser->phone = $request->user_phone;

        $addUser->allow_login = 1;
        $addUser->username = $request->username;
        $addUser->password = Hash::make($request->password);

        $addUser->role_type = 3;
        $addUser->is_belonging_an_area = 1;
        // Assign role

        $addUser->branch_id = $branch_id;

        $addUser->save();
    }
}
